# Generated by Django 4.0.4 on 2022-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
