# Generated by Django 4.0.4 on 2022-07-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambus', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Q',
            new_name='Register',
        ),
    ]
